apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: ib-vs
spec:
  host: ib.f5demo.io
  tls:
    secret: ib-secret
    cert-manager:
      cluster-issuer: letsencrypt-issuer
  externalDNS:
    enable: true
  upstreams:
  - name: demo-app
    service: demo-svc
    port: 80
  routes:
  - path: /
    action:
      pass: demo-app
