apiVersion: appprotect.f5.com/v1beta1
kind: APPolicy
metadata:
  name: example-ap-policy
  namespace: f5se
spec:
  policy:
    name: example-ap-policy
    template:
      name: POLICY_TEMPLATE_NGINX_BASE
    applicationLanguage: utf-8
    enforcementMode: transparent
    server-technologies:
      - serverTechnologyName: Unix/Linux
      - serverTechnologyName: Nginx
      - serverTechnologyName: "Apache/NCSA HTTP Server"
      - serverTechnologyName: PHP
    bot-defense:
      settings:
        isEnabled: true
      mitigations:
        classes:
        - name: trusted-bot
          action: detect
        - name: untrusted-bot
          action: alarm
        - name: malicious-bot
          action: block
---
apiVersion: appprotect.f5.com/v1beta1
kind: APLogConf
metadata:
  name: example-logconf
  namespace: f5se
spec:
  content:
    format: default
    max_message_size: 64k
    max_request_size: any
  filter:
    request_type: illegal
