apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: f5se-example-vs
  namespace: f5se
spec:
  host: f5se-example.f5demo.io
  externalDNS:
    enable: true
  upstreams:
  - name: demo-app
    service: demo-svc
    port: 80
  routes:
  - path: /
    action:
      pass: demo-app
